### Verificar conexión al servidor
GET http://localhost:8000/muebles/

### Consultar todos los muebles
GET http://localhost:8000/muebles/mueble_all

### Consultar un mueble por ID
GET http://localhost:8000/muebles/mueble/30
Accept: application/json

### Consultar un mueble por ID (método directo)
GET http://localhost:8000/muebles/mueble/40
Accept: application/json

### agregar un nuevo mueble
POST http://localhost:8000/muebles/add
Content-Type: application/json

{
    "nombre": "Baserefrigerante",
    "tipo": "cocina",
    "material": "Malla y Metal",
    "precio": 150.50,
    "stock": 100
}

### Eliminar un mueble por ID
DELETE http://localhost:8000/muebles/eliminar/58
Accept: application/json

##--------------------------------------------------------

### Verificar si la rura es publica
GET http://localhost:8000/api/public


### Registro de un nuevo usuario (método directo)
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
    "nom_user": "Camilo",
    "password": "9876"
}


###  Iniciar Sesión para obtener el Token
POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{
    "nom_user": "Angel",
    "password": "11449" 
}

### Consultar usuario actual
GET http://127.0.0.1:8000/api/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjQwMzg5NywianRpIjoiN2IyNWQwMTYtOGFmMy00ZjE5LWI0YmYtZDAzZWJlMmRiMTQyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkFuZ2VsIiwibmJmIjoxNzc2NDAzODk3LCJjc3JmIjoiNjVjNTY2OGMtY2ZkMy00OTdlLThhNmEtNmQyMDM3OTYyOWU1Iiwicm9sZSI6ImFkbWluIn0.ywc_Fj0htH3_yPB-6Q2N8jWxAxsLM8G-1cIZ5HtcGsQ
Accept: application/json


### Obtener perfil del usuario autenticado
GET http://127.0.0.1:8000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjQwMzg5NywianRpIjoiN2IyNWQwMTYtOGFmMy00ZjE5LWI0YmYtZDAzZWJlMmRiMTQyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkFuZ2VsIiwibmJmIjoxNzc2NDAzODk3LCJjc3JmIjoiNjVjNTY2OGMtY2ZkMy00OTdlLThhNmEtNmQyMDM3OTYyOWU1Iiwicm9sZSI6ImFkbWluIn0.ywc_Fj0htH3_yPB-6Q2N8jWxAxsLM8G-1cIZ5HtcGsQ
Accept: application/json


### 2. Usar el Token para ver la lista (Sustituye el código largo)
GET http://127.0.0.1:8000/api/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjQwMzg5NywianRpIjoiN2IyNWQwMTYtOGFmMy00ZjE5LWI0YmYtZDAzZWJlMmRiMTQyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkFuZ2VsIiwibmJmIjoxNzc2NDAzODk3LCJjc3JmIjoiNjVjNTY2OGMtY2ZkMy00OTdlLThhNmEtNmQyMDM3OTYyOWU1Iiwicm9sZSI6ImFkbWluIn0.ywc_Fj0htH3_yPB-6Q2N8jWxAxsLM8G-1cIZ5HtcGsQ
Accept: application/json


### Obtener un nuevo access token usando el REFRESH TOKEN (Correcto)
POST http://127.0.0.1:8000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjQwNDA5OSwianRpIjoiZDI4MGMxMDEtMTA2OS00MDhlLWE5NDMtMTkyM2Q0NWI1YjZhIiwidHlwZSI6InJlZnJlc2giLCJzdWIiOiJBbmdlbCIsIm5iZiI6MTc3NjQwNDA5OSwiY3NyZiI6IjI5YTI1ZTg2LTI0YjItNDJiOS1iZGQ1LThjM2ZhODAyNjNiZiJ9.v60ulol_TVaPeASHUu14mw-9dgpR0nF2GzywO7ngvaY
Accept: application/json


### Revocar el token actual
DELETE http://127.0.0.1:8000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3NjQwNDExNywianRpIjoiNmM0ODI4ZjYtNGNhZS00ZjA3LTkxMzEtODlkYWQ4ZWE4NTdhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IkFuZ2VsIiwibmJmIjoxNzc2NDA0MTE3LCJjc3JmIjoiZTYxM2I2OWMtZmRmZi00MjFkLWFkZDgtZDFjZTY5Y2M1NGVjIiwicm9sZSI6ImFkbWluIn0.EbmJoqJvic5P0bJ9uY2ECyBd0vgDLe80ElZiHEmsx_w
Accept: application/json


### Registro de un nuevo Administrador
POST http://127.0.0.1:8000/auth/register-admin
Content-Type: application/json

{
    "nom_user": "Nikolas",
    "password": "98765"
}


